/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeRouteImport } from './routes/$mode'
import { Route as AuditLanesRouteRouteImport } from './routes/audit-lanes/route'
import { Route as AuditWidthRouteImport } from './routes/audit-width'
import { Route as AuditLanesIndexRouteImport } from './routes/audit-lanes/index'
import { Route as AuditLanesDemoIdRouteImport } from './routes/audit-lanes/$demoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeRoute = ModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLanesRouteRoute = AuditLanesRouteRouteImport.update({
  id: '/audit-lanes',
  path: '/audit-lanes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditWidthRoute = AuditWidthRouteImport.update({
  id: '/audit-width',
  path: '/audit-width',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLanesIndexRoute = AuditLanesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditLanesRouteRoute,
} as any)
const AuditLanesDemoIdRoute = AuditLanesDemoIdRouteImport.update({
  id: '/$demoId',
  path: '/$demoId',
  getParentRoute: () => AuditLanesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-lanes': typeof AuditLanesRouteRouteWithChildren
  '/$mode': typeof ModeRoute
  '/audit-width': typeof AuditWidthRoute
  '/audit-lanes/$demoId': typeof AuditLanesDemoIdRoute
  '/audit-lanes/': typeof AuditLanesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$mode': typeof ModeRoute
  '/audit-width': typeof AuditWidthRoute
  '/audit-lanes/$demoId': typeof AuditLanesDemoIdRoute
  '/audit-lanes': typeof AuditLanesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-lanes': typeof AuditLanesRouteRouteWithChildren
  '/$mode': typeof ModeRoute
  '/audit-width': typeof AuditWidthRoute
  '/audit-lanes/$demoId': typeof AuditLanesDemoIdRoute
  '/audit-lanes/': typeof AuditLanesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-lanes'
    | '/$mode'
    | '/audit-width'
    | '/audit-lanes/$demoId'
    | '/audit-lanes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$mode' | '/audit-width' | '/audit-lanes/$demoId' | '/audit-lanes'
  id:
    | '__root__'
    | '/'
    | '/audit-lanes'
    | '/$mode'
    | '/audit-width'
    | '/audit-lanes/$demoId'
    | '/audit-lanes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLanesRouteRoute: typeof AuditLanesRouteRouteWithChildren
  ModeRoute: typeof ModeRoute
  AuditWidthRoute: typeof AuditWidthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$mode': {
      id: '/$mode'
      path: '/$mode'
      fullPath: '/$mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-lanes': {
      id: '/audit-lanes'
      path: '/audit-lanes'
      fullPath: '/audit-lanes'
      preLoaderRoute: typeof AuditLanesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-width': {
      id: '/audit-width'
      path: '/audit-width'
      fullPath: '/audit-width'
      preLoaderRoute: typeof AuditWidthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-lanes/': {
      id: '/audit-lanes/'
      path: '/'
      fullPath: '/audit-lanes/'
      preLoaderRoute: typeof AuditLanesIndexRouteImport
      parentRoute: typeof AuditLanesRouteRoute
    }
    '/audit-lanes/$demoId': {
      id: '/audit-lanes/$demoId'
      path: '/$demoId'
      fullPath: '/audit-lanes/$demoId'
      preLoaderRoute: typeof AuditLanesDemoIdRouteImport
      parentRoute: typeof AuditLanesRouteRoute
    }
  }
}

interface AuditLanesRouteRouteChildren {
  AuditLanesDemoIdRoute: typeof AuditLanesDemoIdRoute
  AuditLanesIndexRoute: typeof AuditLanesIndexRoute
}

const AuditLanesRouteRouteChildren: AuditLanesRouteRouteChildren = {
  AuditLanesDemoIdRoute: AuditLanesDemoIdRoute,
  AuditLanesIndexRoute: AuditLanesIndexRoute,
}

const AuditLanesRouteRouteWithChildren = AuditLanesRouteRoute._addFileChildren(
  AuditLanesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLanesRouteRoute: AuditLanesRouteRouteWithChildren,
  ModeRoute: ModeRoute,
  AuditWidthRoute: AuditWidthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
