/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123ModeChar125RouteImport } from './routes/{-$mode}'

const Char123ModeChar125Route = Char123ModeChar125RouteImport.update({
  id: '/{-$mode}',
  path: '/{-$mode}',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$mode}': typeof Char123ModeChar125Route
}
export interface FileRoutesByTo {
  '/{-$mode}': typeof Char123ModeChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$mode}': typeof Char123ModeChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/{-$mode}'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$mode}'
  id: '__root__' | '/{-$mode}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123ModeChar125Route: typeof Char123ModeChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$mode}': {
      id: '/{-$mode}'
      path: '/{-$mode}'
      fullPath: '/{-$mode}'
      preLoaderRoute: typeof Char123ModeChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123ModeChar125Route: Char123ModeChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
